### ISSUE TITLE
Release Github Action

### ISSUE THREAD

**Issue by chrbayer84** [salesforce/carbonj#5]
Currently there is no release process for CarbonJ. Ask is to add a GitHub Release action like this one: https://github.com/marketplace/actions/create-a-release
This would do the following things:
- create GitHub artifacts of releases
- push a release version image to dockerhub (should already work)
- push jars to sonatype oss nexus (https://oss.sonatype.org/#welcome)
   --> net new, build is currently not pushing any jars anywhere

The trigger for a release with the Release GitHub Action seems to be by committing a tag prefixed with a "v" like "v1.2.3". This process should also be automated (maybe by a script that is run locally by a developer that checks out a tag branch, pushes it and resets local branch back to master. But even better would be some kind of button that an admin can click on the project page in github that would start the process.

**Comment by twoversionsofme** [comment]
In https://github.com/salesforce/carbonj/pull/7 I've started by creating a distribution that includes the startup shell script and publishing to the GitHubPackages repo on this repository.  I initially got this working on my fork first.  It's not an ideal distribution point, but can be used as a first step.

The process to get it pushed to OSS Sonatype can take a couple days.  It's [documented here](https://central.sonatype.org/pages/ossrh-guide.html).  I've [created a ticket](https://issues.sonatype.org/browse/OSSRH-59611) for pushing artifacts there and once that is completed I'll start that process.

Another option is to use JFrog Bintray and then sync to OSS Sonatype.  From what I've read on some blog posts this is the simplest path.  As a result I've created an account can be shared and a [repo for cabonj](https://dl.bintray.com/salesforce-cc/carbonj) in it.  I'll work on getting this rigged up to push there.

cc: @slodha @chrbayer84
